### ISSUE TITLE
Integrate MISP and Gitlab in docker-compose

### ISSUE THREAD

**Issue by fritterhoff** [hm-seclab/YAFRA#21]
- [x] Integrate MISP (https://github.com/MISP/misp-docker)
- [x] Integrate Gitlab (https://docs.gitlab.com/ee/install/docker.html#install-gitlab-using-docker-compose)

**Comment by DerAlexmeister** [comment]
Add documentation in the docs folder.

**Comment by fritterhoff** [comment]
> 
> 
> Add documentation in the docs folder.

Done

**Comment by fritterhoff** [comment]
Integrated and done.
