### ISSUE TITLE
Remove blacklist from Monthly Branches by default

### ISSUE THREAD

**Issue by DerAlexmeister** [hm-seclab/YAFRA#33]
The blacklist should be removed from monthly branches.

**Comment by p2h5** [comment]
To keep the branch structure clean, it could be good practice to remove the blacklist from the monthly branches and only keep relevant data.

**Comment by p2h5** [comment]
Fix in https://github.com/hm-seclab/YAFRA/pull/49.

**Comment by p2h5** [comment]
Can be closed.
