### ISSUE TITLE
Add rules for removing special chars from branch title

### ISSUE THREAD

**Issue by p2h5** [hm-seclab/YAFRA#39]
**Describe the bug**
Getting errors, while creating new branches for reports, which contains special chars in the title.

**To Reproduce**
1. Create a new Report with a special char in the title e.g. @'/
2. Upload it with yafra to gitlab

**Expected behavior**
Creation of a new branch and report by title in gitlab.

**Possible solution**
import re
result = re.sub('[^a-zA-Z0-9]', '', '<STRING>')

**Comment by DerAlexmeister** [comment]
Don't except any character beside [a-zA-Z0-9-]

**Comment by p2h5** [comment]
Fix in https://github.com/hm-seclab/YAFRA/pull/47.
